dist: trusty

language: node_js
node_js:
    - 12.18.3
install:
    - sudo apt-get install -y dpkg
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
    - sudo apt-key update
    - sudo apt-get update --allow-unauthenticated -q
    - sudo apt-get install -q google-chrome-stable --allow-unauthenticated

branches:
    only:
        - master

script:
    - npm install
    - npm test
    - ./node_modules/.bin/ng build --prod --base-href=/ngx-daterangepicker-material/

after_success:
    - ./node_modules/.bin/ngh --dir demo/dist --repo=https://GH_TOKEN@github.com/fetrarij/ngx-daterangepicker-material.git

notifications:
    email:
        on_failure: change
        on_success: change
